### PR TITLE
WIP big redo with bitcoin-block and full tx, segwit and merkle handling

### PR DESCRIPTION
**Pull request by rvagg**
First commit switches old code to https://ghub.io/bitcoin-block from bitcoinjs and keeps existing tests.

Remainder are basically a rewrite. **Don’t look too hard yet, it’s very much a WIP**. I’m trying to use the https://github.com/mikeal/js-multiformats interface and it certainly simplifies things quite a lot.

Each of the fixtures have been updated with:

 * JSON form, extracted directly from the bitcoin-cli, unmodified
 * transaction metadata that lists hash, txid and byte location inside the raw block so we can test _all of them_ (quite a lot, 3731 all up, only 8 that are segwit though, I might have to include a more modern block with more segwit).

Proven working `bitcoin-block` and `bitcoin-tx` codecs for whole blocks and there’s an encode for blocks with no-witness data but you have to take a back-door to get to that, there’s not really a way to include that as part of the js-multiformats interface (and probably shouldn’t be, but it might be worth discussing at some point). I still need to do the merkle structures which will be `bitcoin-tx` but 64-bytes long blocks, plus an additional codec that will probably be named `bitcoin-witness-commitment` for a 64-byte block.

### CODE REVIEW

**Comment by vmx** [comment]
I had a soft look at it, it really looks promising.

**Comment by rvagg** [comment]
Thinking that maybe we should publish this new work as `@ipld/bitcoin` in a new repo, like the new `@ipld/dag-cbor` and `@ipld/dag-json` as a break from the previous generation. It's now completely different from the old code, except for the test fixtures! The API has changed entirely; you could use multiformats/legacy to get the old API back but maybe we should take the approach of archiving these older libraries and publishing fresh ones.
Thoughts @vmx?

**Comment by vmx** [comment]
> Thinking that maybe we should publish this new work as `@ipld/bitcoin` in a new repo,

Yes I think that makes sense. Given that we change all of the underlying libraries, I think a clear cut makes things also easier for up-stream maintainers. Then it's clear signal "hey, you probably need a change a lot in your code if you want to use this library as intended" (we have a smoother upgrade path through the legacy API, but ideally people will just use the new API).

**Comment by rvagg** [comment]
ok, so a new repo name, should it just be `ipld/js-bitcoin`? I think this matches the pattern @mikeal is establishing

**Comment by rvagg** [comment]
I've pushed this as `master` to https://github.com/rvagg/js-bitcoin. Docs are done and it should be ready to roll. I propose we move that repo into the ipld org and publish as `@ipld/bitcoin`.

**Pull request closed without merging**
