### PR TITLE
[WIP] feat: async await

### PR DESCRIPTION
**Pull request by hacdias**
More background about this effort: https://github.com/ipfs/js-ipfs/issues/1670.

**Depends on:**
- https://github.com/ipld/interface-ipld-format/pull/47
- (Coming PR for `multihashing-async` module)

### CODE REVIEW

**Comment by hacdias** [comment]
@alanshaw I believe AppVeyor should be disabled on this repo since we have no config file for it. Or we can just add one.

**Comment by hacdias** [comment]
@alanshaw what's the state of this?

**Comment by vmx** [comment]
@hacdias https://github.com/ipfs/js-ipfs/issues/1670#issuecomment-453962298

**Comment by vmx** [comment]
Superseded by https://github.com/ipld/js-ipld-bitcoin/pull/48.

**Pull request closed without merging**
